PaginationMetaObject:
  type: object
  properties:
    current_page:
      type: integer
      example: 3
    next_page:
      type: integer
      example: 4
    prev_page:
      type: integer
      example: 2
    total_pages:
      type: integer
      example: 10
    total_count:
      type: integer
      example: 198
